const $=id=>document.getElementById(id);
let selectedSize='M',artUrl='assets/wolf-moon.png',blobUrl=null;
document.querySelectorAll('.sizes button').forEach(el=>{el.setAttribute('aria-pressed',el.classList.contains('selected'));el.addEventListener('click',()=>{selectedSize=el.textContent;document.querySelectorAll('.sizes button').forEach(b=>{b.classList.toggle('selected',b===el);b.setAttribute('aria-pressed',b===el)});$('status').textContent=`Size ${selectedSize} selected. Your design is ready to download.`})});
function setArt(src){artUrl=src;document.querySelectorAll('.design').forEach(img=>img.src=src)}
$('artwork').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>10*1024*1024){$('status').textContent='Choose a PNG, JPG or WebP image under 10 MB.';e.target.value='';return}const url=URL.createObjectURL(f);const probe=new Image();probe.src=url;try{await probe.decode();if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=url;setArt(url);$('status').textContent=`${f.name} is now on your tee and in the story.`}catch{URL.revokeObjectURL(url);$('status').textContent='This image could not be opened. Please choose another file.'}});
$('reset').addEventListener('click',()=>{setArt('assets/wolf-moon.png');if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=null;$('artwork').value='';$('status').textContent='Wolf and moon graphic restored.'});
const loadImage=src=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=reject;im.src=src});
$('download').addEventListener('click',async()=>{const btn=$('download');btn.disabled=true;try{const [shirt,art]=await Promise.all([loadImage('assets/shirt.png'),loadImage(artUrl)]);const canvas=document.createElement('canvas');canvas.width=shirt.naturalWidth;canvas.height=shirt.naturalHeight;const ctx=canvas.getContext('2d');ctx.drawImage(shirt,0,0);const boxW=canvas.width*.28,boxH=canvas.height*.30,scale=Math.min(boxW/art.naturalWidth,boxH/art.naturalHeight),w=art.naturalWidth*scale,h=art.naturalHeight*scale;ctx.globalCompositeOperation='multiply';ctx.drawImage(art,canvas.width*.36+(boxW-w)/2,canvas.height*.32+(boxH-h)/2,w,h);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));if(!blob)throw Error();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`inkind-your-design-${selectedSize}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('status').textContent=`Your size ${selectedSize} transparent T-shirt preview has been downloaded.`}catch{$('status').textContent='Could not download the preview. Please try again.'}finally{btn.disabled=false}});

